### ISSUE TITLE
mibidata module?

### ISSUE THREAD

**Issue by HoxB8** [angelolab/segmentation#142]
Hello, I installed the docker and tried to run the pre-processing script in a new Jupyter notebook file inside the segmentation folder.  when I try to import all the packages, it says there's no module named 'mibidata'.  

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-37fb882e36e2> in <module>
      6 from skimage.measure import label
      7 
----> 8 from segmentation.utils import data_utils, io_utils
      9 
     10 # extract cHL data

~/Dropbox/DB Lab Data/MIBI related/DeepCell Testing/segmentation/segmentation/utils/data_utils.py in <module>
      7 import numpy as np
      8 import xarray as xr
----> 9 from mibidata import tiff
     10 
     11 

ModuleNotFoundError: No module named 'mibidata'

**Comment by ackagel** [comment]
It looks like your jupyter notebook is not actually running in the docker.  Did you copy/use the link from the output of `start_docker.sh`?

**Comment by HoxB8** [comment]
Thanks for the quick reply. 

I tried to run start_docker.sh (making sure to eliminate unnecessary spaces, which I saw could cause problems), but I keep getting this error.

bash start_docker.sh
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by ackagel** [comment]
It looks like there was a bug in our `start_docker.sh` file, but we'll release a fix for it later today.  

In the meantime, here's a corrected version of that file which should get you up and running.  Delete the old `start_docker.sh` file, put this new version in its place, and rename the extension from '.txt' to '.sh'.

[start_docker.txt](https://github.com/angelolab/segmentation/files/5017708/start_docker.txt)

Sorry for the trouble!  Feel free to let us know if you have any more issues!

**Comment by HoxB8** [comment]
Thanks, adding the quotations worked!  (Weirdly, a colleague ran the code with old start_docker.sh and it generated the link just fine)

**Comment by ackagel** [comment]
Awesome!  Yeah, the old version only breaks when there are spaces in folder-names, but the quotes make sure bash doesn't have a melt-down over it.  Great to hear that it's working for you now!
