### ISSUE TITLE
Uploading Multidimensional Tiffs for Segmentation

### ISSUE THREAD

**Issue by HoxB8** [angelolab/segmentation#145]
Hello, I'm going through the pre-processing procedures and am uploading a MassCorrected-Filtered.tiff as a multidimensional tiff.  I set the MIBItiff parameter to True.  My nuc marker is "dsDNA" and my membrane is 'CD45'.  Such as below.  *When I try to load channels load channels to be included in deepcell data I get an error regarding indexing.  Is it not recognizing the channels?**

MIBItiff = True
MIBItiff_suffix = "-MassCorrected-Filtered.tiff"
nucs = ['dsDNA']
mems = ['CD45']
data_utils.validate_paths([data_dir,tiff_dir,deepcell_dir, ])
points = os.listdir(tiff_dir)
points = [point for point in points if os.path.isdir(tiff_dir + point) and point.startswith("Point")]
if MIBItiff:
    points = [point for point in points if point.endswith(MIBItiff_suffix)]

*

channels = (nucs if nucs else []) + (mems if mems else [])
if MIBItiff:
    data_xr = data_utils.load_imgs_from_mibitiff(tiff_dir, mibitiff_files=points, channels=channels)
else:
    data_xr = data_utils.load_imgs_from_tree(tiff_dir, img_sub_folder="TIFs", fovs=points, imgs=channels)
data_utils.generate_deepcell_input(data_xr, deepcell_dir, nucs, mems)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-28-3b9611fcca6e> in <module>
      2 channels = (nucs if nucs else []) + (mems if mems else [])
      3 if MIBItiff:
----> 4     data_xr = data_utils.load_imgs_from_mibitiff(tiff_dir, mibitiff_files=points, channels=channels)
      5 else:
      6     data_xr = data_utils.load_imgs_from_tree(tiff_dir, img_sub_folder="TIFs", fovs=points, imgs=channels)

/usr/local/lib/python3.6/site-packages/segmentation/utils/data_utils.py in load_imgs_from_mibitiff(data_dir, mibitiff_files, channels, delimiter, dtype)
     73                       for mt_file in mibitiff_files]
     74 
---> 75     test_img = io.imread(mibitiff_files[0], plugin='tifffile')
     76 
     77     # check to make sure that float dtype was supplied if image data is float

IndexError: list index out of range

**Comment by ackagel** [comment]
what is the full name of one of the MIBItiff files you're uploading?

**Comment by HoxB8** [comment]
The full name is "20200522_MIBI_Titration_Tonsil_A-MassCorrected-Filtered.tiff"

**Comment by ackagel** [comment]
Great!  So in the third code cell of the notebook, you should see the line:
`points = [point for point in points if os.path.isdir(tiff_dir + point) and point.startswith("Point")]`

If you remove this line, it should work correctly.  Sorry about that!  Please let us know if another problem occurs.

**Comment by HoxB8** [comment]
Got it thanks!  I was able to get the segmentation to work after this.
