### ISSUE TITLE
generate_expression_matrix() requires int labels but deepcell produces float labels

### ISSUE THREAD

**Issue by HoxB8** [angelolab/segmentation#147]
Hello, I'm trying to get the normalized_data.csv after segmentation.  I used ImageJ to generate individual grayscale images of each channel then use single channel inputs for segmentation.  When running the post-processing script, I am able to get the segmented masked overlaid on the images.  However, when I try to run the script to generate the expression matrices I get the 'KeyError: "not all values found in index 'fovs'".  Thanks in advance for your help.

I've pasted the error below:

img_sub_folder = "TIFs"
if not points:
    # load channel data
    all_points = os.listdir(tiff_dir)
    all_points = [point for point in all_points if os.path.isdir(os.path.join(tiff_dir, point))
                  and point.startswith("Point")]
    points = all_points
points.sort()

single_cell_dir = base_dir + "single_cell_output"

if not os.path.exists(single_cell_dir):
    os.makedirs(single_cell_dir)

batch_size = 5
cohort_len = len(points)
num_batch = int(np.floor(cohort_len / batch_size))
combined_normalized_data = pd.DataFrame()
combined_transformed_data = pd.DataFrame()

for i in range(num_batch):
    current_points = points[i * batch_size:(i + 1) * batch_size]
    image_data = data_utils.load_imgs_from_tree(data_dir=tiff_dir, img_sub_folder=img_sub_folder, 
                                                      fovs=current_points)
    current_labels = segmentation_labels.loc[current_points, :, :, :]
    
    normalized_data, transformed_data = segmentation_utils.generate_expression_matrix(segmentation_labels=current_labels, image_data=image_data)
    
    combined_normalized_data = combined_normalized_data.append(normalized_data)
    combined_transformed_data = combined_transformed_data.append(transformed_data)
if cohort_len % batch_size != 0:
    current_points = points[num_batch * batch_size:]
    image_data = data_utils.load_imgs_from_tree(data_dir=tiff_dir, img_sub_folder=img_sub_folder, fovs=current_points)
    current_labels = segmentation_labels.loc[current_points, :, :, :]
    

    normalized_data, transformed_data = segmentation_utils.generate_expression_matrix(segmentation_labels=current_labels, image_data=image_data)
    
    combined_normalized_data = combined_normalized_data.append(normalized_data)
    combined_transformed_data = combined_transformed_data.append(transformed_data)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-f4179c5fe803> in <module>
     21     current_points = points[num_batch * batch_size:]
     22     image_data = data_utils.load_imgs_from_tree(data_dir=tiff_dir, img_sub_folder=img_sub_folder, fovs=current_points)
---> 23     current_labels = segmentation_labels.loc[current_points, :, :, :]
     24 
     25     # segment the imaging data

/usr/local/lib/python3.6/site-packages/xarray/core/dataarray.py in __getitem__(self, key)
    124             labels = indexing.expanded_indexer(key, self.data_array.ndim)
    125             key = dict(zip(self.data_array.dims, labels))
--> 126         return self.data_array.sel(**key)
    127 
    128     def __setitem__(self, key, value) -> None:

/usr/local/lib/python3.6/site-packages/xarray/core/dataarray.py in sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
    962         ds = self._to_temp_dataset().sel(
    963             indexers=indexers, drop=drop, method=method, tolerance=tolerance,
--> 964             **indexers_kwargs)
    965         return self._from_temp_dataset(ds)
    966 

/usr/local/lib/python3.6/site-packages/xarray/core/dataset.py in sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   1796         indexers = either_dict_or_kwargs(indexers, indexers_kwargs, 'sel')
   1797         pos_indexers, new_indexes = remap_label_indexers(
-> 1798             self, indexers=indexers, method=method, tolerance=tolerance)
   1799         result = self.isel(indexers=pos_indexers, drop=drop)
   1800         return result._overwrite_indexes(new_indexes)

/usr/local/lib/python3.6/site-packages/xarray/core/coordinates.py in remap_label_indexers(obj, indexers, method, tolerance, **indexers_kwargs)
    323 
    324     pos_indexers, new_indexes = indexing.remap_label_indexers(
--> 325         obj, v_indexers, method=method, tolerance=tolerance
    326     )
    327     # attach indexer's coordinate to pos_indexers

/usr/local/lib/python3.6/site-packages/xarray/core/indexing.py in remap_label_indexers(data_obj, indexers, method, tolerance)
    250         else:
    251             idxr, new_idx = convert_label_indexer(index, label,
--> 252                                                   dim, method, tolerance)
    253             pos_indexers[dim] = idxr
    254             if new_idx is not None:

/usr/local/lib/python3.6/site-packages/xarray/core/indexing.py in convert_label_indexer(index, label, index_name, method, tolerance)
    189             if np.any(indexer < 0):
    190                 raise KeyError('not all values found in index %r'
--> 191                                % index_name)
    192     return indexer, new_index
    193 

KeyError: "not all values found in index 'fovs'"

**Comment by ngreenwald** [comment]
It looks like the `segmentation_labels` array doesn't contain a segmentation mask that matches the `current_points` names. Hence not all values found. You can print out the names within the current_points by just print(current_points), and print out the names in the xarray with print(segmentation_labels.fovs.values). This should help to figure out where the name mismatch is coming from.

**Comment by HoxB8** [comment]
Thanks. I think  that helped, but now I get a different error...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-5562be1d6520> in <module>
     31 
     32     # segment the imaging data
---> 33     normalized_data, transformed_data = segmentation_utils.generate_expression_matrix(segmentation_labels=current_labels, image_data=image_data)
     34 
     35     combined_normalized_data = combined_normalized_data.append(normalized_data)

/usr/local/lib/python3.6/site-packages/segmentation/utils/segmentation_utils.py in generate_expression_matrix(segmentation_labels, image_data, nuclear_counts)
    487         # extract the counts per cell for each marker
    488         marker_counts = compute_marker_counts(image_data.loc[fov, :, :, :], segmentation_label,
--> 489                                               nuclear_counts=nuclear_counts)
    490 
    491         # remove the cell corresponding to background

/usr/local/lib/python3.6/site-packages/segmentation/utils/segmentation_utils.py in compute_marker_counts(input_images, segmentation_masks, nuclear_counts)
    390     # get regionprops for each cell
    391     cell_props = pd.DataFrame(regionprops_table(segmentation_masks.loc[:, :, 'whole_cell'].values,
--> 392                                                 properties=object_properties))
    393 
    394     if nuclear_counts:

/usr/local/lib/python3.6/site-packages/skimage/measure/_regionprops.py in regionprops_table(label_image, intensity_image, properties, cache, separator)
    622     """
    623     regions = regionprops(label_image, intensity_image=intensity_image,
--> 624                           cache=cache)
    625     return _props_to_dict(regions, properties=properties, separator=separator)
    626 

/usr/local/lib/python3.6/site-packages/skimage/measure/_regionprops.py in regionprops(label_image, intensity_image, cache, coordinates)
    839 
    840     if not np.issubdtype(label_image.dtype, np.integer):
--> 841         raise TypeError('Label image must be of integer type.')
    842 
    843     if coordinates is not None:

TypeError: Label image must be of integer type.

**Comment by ngreenwald** [comment]
Oh, hmm. That's a bug that we didn't catch when we switched over to using the deepcell.org website. It returns the labels as floats, not ints. 

As a workaround for now, if you add this line right after current_labels gets created, it will convert it to an int

```
import xarray as xr
current_labels = xr.DataArray(current_labels.values.astype('int'), coords=current_labels.coords, dims=current_labels.dims)
```

**Comment by HoxB8** [comment]
Got it and it works! Thank you!

**Comment by HoxB8** [comment]
I'm trying to see if I could use segment a multi-channel tif.  The expression matrix script runs, but the csv files are empty.  Is that because the channel information in the metadata is not read?

**Comment by ngreenwald** [comment]
Yes, right now it only works for folders of TIFs. We're updating that part of the code tomorrow, we can add that in.

**Comment by ngreenwald** [comment]
There's a couple options to resolve this; the long-term fix is to modify deepcell.org to to generate ints instead of floats for labels. We could either cast to int inside of compute_expression_matrix, or we could modify segmentation_labels when the xarray is being created/when the TIFs are read in

**Comment by ackagel** [comment]
I think casting to int when reading TIFs into segmentation_labels is the easiest, most maintainable solution; we can include a warning message for the casting to int as well.

**Comment by ngreenwald** [comment]
Okay great, sounds good!
