### ISSUE TITLE
segmentation_utils.watershed_transform crashes

### ISSUE THREAD

**Issue by mapazarr** [angelolab/segmentation#45]
@ngreenwald I am having problems with the following line of code:
https://github.com/angelolab/segmentation/blob/dc2c06ebea1d1a45f453213ec1012bed4d1a5ac7/segmentation/utils/segmentation_utils.py#L54
basically, it tries to flatten the `overlay_channels` input variable from a list of lists into a single list.
But if I give the input variable as a regular list of strings such as:
```
overlay_channels = ["HH3", "Membrane"]
```
it will transform it into a list of characters:
```
flat_channels = ['H', 'H', '3', 'M', 'e', 'm', 'b', 'r', 'a', 'n', 'e']
```
causing the function to crash, because it cannot find the channels.

Unfortunately the `overlay_channels` input variable is not explained in the docstring of the function, so before creating a PR addressing this issue I wanted to clarify:
- What is the expected type of this variable?
- Is there a need to flatten the list of lists?

In my opinion, it should just be a regular list of strings, in which case the flattening is unnecessary.

In case there is a use case for list of lists, we need something more elaborate in order to catch the use case of single lists.

Let me please know your thoughts and I will create a PR to address this issue correspondingly.

**Comment by ngreenwald** [comment]
Yeah, that's my fault. 
I just pushed a commit yesterday that breaks this. Each entry needs to be a string. 

If you look in the newest post-processing script:https://github.com/angelolab/segmentation/blob/master/scripts/Deepcell_Postprocessing.ipynb

The input now has to be of the form overlay_channels = [["HH3"], ["Membrane"]]

The reason for the change is that it now looks at the number of entries in the sub list, and if more than one, plots them as overlay

**Comment by ngreenwald** [comment]
One option would be to check if list of lists, and only flatten in that case? That way the input could just be a regular list, and optionally one of the entires could be a sub-list, rather than requiring everything to be lists? Let me know what you think

**Comment by mapazarr** [comment]
What about having the input be a dictionary with 2 keys: `nucear` and `membrane`? We could then check the type of the value of each key and if it's a list, then plot each of the elements as overlay, if not, just plot the value directly.

**Comment by ngreenwald** [comment]
Oh, I like that! Do you think having a dictionary with values of either
strings or lists is better than having a list of lists?

The only issue is that the keys won't be nuclear or membrane. For example,
the current jupyter template first makes an overlay of just DNA, then an
overlay of just membrane, then an overlay with both DNA and membrane. You
could imagine that for datasets with three segmentation markers, you might
have an increasing number of combinations that you'd like to overlay, which
is why I went with a list of lists.

The other option would be to have it be a list, with elements either
strings or lists, and then just check along the way if each element is a
string or a list. What do you think makes the most sense?

**Comment by mapazarr** [comment]
Oh ok, I had a look at the changes (I had totally missed your PR) and it doesn't make much sense to use the dictionary in that case. I guess the list of lists is ok, we should document it in the function though.
